### ISSUE TITLE
Update http://www.freecol.org/ with GitHub links

### ISSUE THREAD

**Issue by paulvi** [FreeCol/www.freecol.org#1]
Update http://www.freecol.org/ with GitHub links, and nightly builds

Is it easy to push change from here to real http://www.freecol.org site?

**Comment by wintertime** [comment]
I've done it on the real site, but kept the code in [main repo](https://sourceforge.net/p/freecol/git/ci/master/tree/).
This repository is currently outdated, but we plan on updating it.
